import type { Metadata } from "next";
import { Activity, activities } from "@/constant/activities"

interface LayoutProps {
  params: { slug: string };
  chidren: React.ReactNode;
}

const getActivity = (slug: string): Activity | undefined => {
  return activities.find((a) => a.slug === slug)
}

// export const metadata: Metadata = {
//   title: `กิจกรรมของสมาคมวิทยุสมัครเล่นจังหวัดพิจิตร`,
//   description: "Generated by create next app",
// };

export async function generateMetadata({ params }: LayoutProps): Promise<Metadata> {
  const activity = getActivity(params.slug)

  if (!activity) {
    return {
      title: "Not Found",
      description: "Activity not found",
      robots: "noindex, nofollow",
    }
  }

  return {
    title: `${activity.title} - HS6AJ`,
    description: activity.description,
    keywords: ["hs6aj", "hamradio", "amateur radio", "thailand"],
    authors: [{ name: "HS6AJ", url: "https://test.test/" }],
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div className="min-h-screen">

      {children}

    </div>
  );
}
