import type { Metadata } from "next";
import { articles, Articles  } from "@/constant/articles"

interface LayoutProps {
  params: { slug: string };
  chidren: React.ReactNode;
}

const getArticle = (slug: string): Articles | undefined => {
  return articles.find((a) => a.slug === slug)
}

// export const metadata: Metadata = {
//   title: `กิจกรรมของสมาคมวิทยุสมัครเล่นจังหวัดพิจิตร`,
//   description: "Generated by create next app",
// };

export async function generateMetadata({ params }: LayoutProps): Promise<Metadata> {
  const article = getArticle(params.slug)

  if (!article) {
    return {
      title: "Not Found",
      description: "Article not found",
      robots: "noindex, nofollow",
    }
  }

  return {
    title: `${article.title} - HS6AJ`,
    description: article.description,
    keywords: ["hs6aj", "hamradio", "amateur radio", "thailand"],
    authors: [{ name: "HS6AJ", url: "https://test.test/" }],
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div className="min-h-screen">

      {children}

    </div>
  );
}
